name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target: ['x86_64-unknown-linux-gnu', 'aarch64-unknown-linux-gnu', 'x86_64-pc-windows-msvc', 'x86_64-apple-darwin', 'aarch64-apple-darwin']
        include:
          - target: 'x86_64-pc-windows-msvc'
            os: windows-latest
            suffix: '.exe'
          - target: 'x86_64-apple-darwin'
            os: macos-latest
          - target: 'x86_64-apple-darwin'
            os: macos-latest
        
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    steps:
    - uses: actions/checkout@v3
    
    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}
        path: target/${{ matrix.target }}/release/whatip${{ matrix.suffix }}
